name: Package

on:
  push:
    tags:
      - "*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Get Tag Name
        run: echo "Tag name is ${GITHUB_REF#refs/tags/}"
      - name: Chose JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        run: |
          ./gradlew clean build
      - name: Jetbrains Upload
        shell: cmd
        run: |
          curl -i --header "Authorization: Bearer ${{ secrets.jetbrainsToken }}" -F pluginId=24872 -F file=@build/distributions/ModMultiVersion-${GITHUB_REF#refs/tags/}.zip https://plugins.jetbrains.com/plugin/uploadPlugin

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: ${GITHUB_REF#refs/tags/}
          title: ${GITHUB_REF#refs/tags/}
          prerelease: false
          files: |
            build/distributions/*