name: Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Get version
        shell: pwsh
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          echo ${{ steps.get_version.outputs.VERSION }}
      - name: Chose JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        run: |
          ./gradlew clean build

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
          title: ${{ steps.get_version.outputs.VERSION }}
          prerelease: false
          files: |
            build/distributions/*